### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by vionemc** [Full360Solutions/angularjs-typeahead-dropdown#10]
I've tried to open the documentation here http://full360solutions.github.io/angularjs-typeahead-dropdown/

The documentation site seems broken and not leading to any documentation. I think it's fatal

**Comment by agray** [comment]
In what way do you think it's broken?

**Comment by vionemc** [comment]
Just open the link. I can only see the header. I checked the HTML, the
content is not loaded.

**Comment by kinow** [comment]
The documentation is not very extensive, but is definitely there @vionemc 

@agray, I believe this issue can be closed.

@vionemc in case you have some spare time to enhance the documentation, please feel free to send us a pull request with your suggestions :-)

**Comment by agray** [comment]
Will process pull requests quickly.  What more documentation over the example http://full360solutions.github.io/angularjs-typeahead-dropdown were you looking for?

**Comment by vionemc** [comment]
I think it was just some web error. The documentation is okay now. Previously the content didn't show up, just blank.
