### ISSUE TITLE
The component doesn't support the ng-disabled attribute

### ISSUE THREAD

**Issue by Snooze-** [Full360Solutions/angularjs-typeahead-dropdown#3]
## To Reporduce

Create a component like:

``` html
<typeahead-dropdown ng-disabled="true" id="ex1" ng-model="ex1model" options="ex1data" config="ex1config"></typeahead-dropdown>
```
## Expected Behaviour

The component becomes disabled similar to setting `ng-disabled="true"` on a `select` element.
## Actual Behaviour

No change to the component.

**Comment by agray** [comment]
Have merged your pull request.
