### ISSUE TITLE
Angular how can we edit the selected value and also it gets reflected on model

### ISSUE THREAD

**Issue by saroj990** [Full360Solutions/angularjs-typeahead-dropdown#5]
How can we edit the selected value inside the text box  and also it gets reflected on model and view both in angualr js and bind a custom event to select.

**Comment by agray** [comment]
Doesn't the demo at http://full360solutions.github.io/angularjs-typeahead-dropdown show the value binding back to the model?

**Comment by aniamy** [comment]
The demo only shows the model when the user does select an option. But it doesn't show the input value. For example, the user start typing "br". I want to get that "br" so I can call my server with "br" as a parameter so it would return the [Brian, Bruno] list.
