### ISSUE TITLE
With Angular.js 1.4 console shows a set of deprication warnings

### ISSUE THREAD

**Issue by Stwissel** [Full360Solutions/angularjs-typeahead-dropdown#6]
With angular.js 1.4 (1.4.7) when opening a popup there are some deprecation warnings:

```
    angular.js (line 12477)
    typeaheadParser is now deprecated. Use uibTypeaheadParser instead. 
    DropdownController is now deprecated. Use UibDropdownController instead.
    typeahead is now deprecated. Use uib-typeahead instead.
    dropdown-toggle is now deprecated. Use uib-dropdown-toggle instead.
    dropdown-menu is now deprecated. Use uib-dropdown-menu instead.
    dropdown is now deprecated. Use uib-dropdown instead.
    dropdown-menu is now deprecated. Use uib-dropdown-menu instead.
    typeahead-popup is now deprecated. Use uib-typeahead-popup instead. 
```

Is there a fix planned?

**Comment by agray** [comment]
Thank you for your interest and for submitting this issue.

From what I have read the fix is pretty straightforward.  Looks like we just need to add the uib prefix as suggested.

I'll try and take a look at this over the weekend. Feel free to submit a pull request, if urgent

**Comment by Stwissel** [comment]
Thx appreciate the attention

—
Pegged on Glas Stephan H. Wissel

+65 9667 3269

@notessensei

**Comment by agray** [comment]
I've updated the versions to the latest versions.  See Demo.  It seems to be working, where are you seeing the deprecation warnings?  I am not seeing them, or more accurately not currently reproducing them.

Are you able to provide repro steps?

**Comment by agray** [comment]
No response received.  Assuming this is fixed.  Please reopen if still an issue

**Comment by Eanimal** [comment]
Hello agray,

This 'deprecated' problem still exists. You are currently using ui-bootstrap.js version 0.14.3, latest version is  1.3.3 . And there are some changes like 'uib-' prefix , so it does not work with this version. I have taken screenshot for you to see [https://i.imgsafe.org/1ded7b78c2.jpg](url) . Please see if you can fix this.
Thanks a lot!

**Comment by fullcirclesolutions** [comment]
Thanks for the image we'll take a look.

**Comment by Deepti03** [comment]
Hi,
I am also facing this issue on IE 11 browser on other browser I am not getting depricated warning messages, can anyone please help to resolve it ?
![uiwarning](https://cloud.githubusercontent.com/assets/23023776/19635281/c90498ca-99de-11e6-9c4b-7c0cf1f42184.png)
