### ISSUE TITLE
Add an id to the input to get text value

### ISSUE THREAD

**Issue by aniamy** [Full360Solutions/angularjs-typeahead-dropdown#7]
Is there a way to get the text the user is typing? (before they select an option)
I'm trying to add some functionality so I can make a rest call to the server based on what the user is typing to fill the list based on the result but I'm not able to get that value.

**Comment by RamiMustaklem** [comment]
If anyone found a way for this issue to be solved please let me know. I'm also trying to get options from an api but I can't seem to able to get the value either.

**Comment by agray** [comment]
Investigating...

**Comment by agray** [comment]
I've added an id to the input in the template cache to assist with this use case. @aniamy @RamiMustaklem could you please retest and let me know if this solves the issue
