### ISSUE TITLE
List gets corrupt 

### ISSUE THREAD

**Issue by DKS1974** [Full360Solutions/angularjs-typeahead-dropdown#9]
Selecte a value from the list and it updated the input text box.

Starting typing and then select from the list that appears works well.

Edit it with some value that does not exist in the list and hit the return 

It starts overwriting objects in the list

**Comment by SKBanks** [comment]
Seeing this as well...any planned updates to fix this?  Even the tool in your example corrupts the data, and it only took about 10 seconds to encounter this.

**Comment by MikaereC-zz** [comment]
If you select an item from the dropdown, then typing backspace deletes the property specified in the config optionLabel. This kind of wrecks the usefulness of this control.  Any plan to fix this ?

**Comment by agray** [comment]
Should be fixed now.
